### PR TITLE
merged all three repos together

### PR DESCRIPTION
**Pull request by eidolonFIRE**
Putting all three repos into one for convenience.

`./server/src`
`./client/src`
`./api/src`

### CODE REVIEW

**Review by gitToad — APPROVED** [review]

**Review by adrienbernede — COMMENTED** [review]
I found this:
https://stackoverflow.com/questions/62802198/ts-cannot-find-module-from-node-modules-when-importing-an-image

I will have a look later on.

**Comment by eidolonFIRE** [comment]
@adrienbernede What's odd is that that import worked just fine before. Something about the directory structure broke it.
It uses this file to do some magic to tell webpack to copy this file out of the `node_modules/...` resource to the `./dist` output.
  https://github.com/eidolonFIRE/xcNav/blob/main/src/ts/typings/custom/import-png.d.ts

It also works locally which leads me to believe it's something about the github job that isn't happy with this.

**Comment by eidolonFIRE** [comment]
Well, derp, now that I point that out I realized the file is missing.... :disappointed: 
It was blocked by the `.gitignore`

**Comment by adrienbernede** [comment]
Glad that automated testing served its purpose 👍🏻 .

**Comment by adrienbernede** [comment]
Hmm, I also saw the typo, but forgot to mention it :p

**Pull request merged**
